app:
  e-library-url: ${ELIBRARY_URL}

gsheets:
  credentials: ${CREDENTIALS_PATH}
  sheet-id: ${SHEET_ID}
  oauth-port: ${OAUTH_PORT}

spring:
  application:
    name: eLibraryApi

server:
  port: ${PORT}

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
    oauth:
      app-name: eLibraryAPI