name: Docker build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-dcoker-image:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      packages: write
      pull-requests: write

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/wolfofbad/elibraryApi:latest